<?php
require_once '../includes/auth.php';
require_once '../includes/db.php';
require_once '../includes/fifo_inventory_helper.php';

$user_id = (int)($_SESSION['user_id'] ?? 0);
$return_id = max(0, (int)($_GET['id'] ?? 0));
$branch_id = selected_branch_id($conn, true);
$return = mysqli_fetch_assoc(mysqli_query($conn, "SELECT dr.*,p.product_name,p.sku,b.branch_name,b.branch_code,b.is_head_office FROM stock_damage_returns dr INNER JOIN products p ON p.id=dr.product_id AND p.user_id=dr.user_id INNER JOIN branches b ON b.id=dr.branch_id AND b.user_id=dr.user_id WHERE dr.id={$return_id} AND dr.user_id={$user_id} AND dr.branch_id={$branch_id}"));
if (!$return) { http_response_code(404); exit('Damaged return not found.'); }
$company = mysqli_fetch_assoc(mysqli_query($conn, "SELECT * FROM users WHERE id={$user_id}")) ?: [];
$company_name = trim((string)($company['company_name'] ?? $company['name'] ?? '')) ?: 'Company';
$branch_name = ($return['is_head_office'] ? 'Head Office' : $return['branch_name']) . (!empty($return['branch_code']) ? ' [' . $return['branch_code'] . ']' : '');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Damaged Return <?= (int)$return['id'] ?></title><style>*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#1f2937;margin:0;background:#f3f4f6}.sheet{width:210mm;min-height:297mm;margin:16px auto;background:#fff;padding:18mm}.toolbar{width:210mm;margin:16px auto;text-align:right}.toolbar button{padding:8px 16px;border:0;border-radius:4px;background:#2563eb;color:#fff;cursor:pointer}.head{display:flex;justify-content:space-between;border-bottom:2px solid #dc2626;padding-bottom:14px;margin-bottom:20px}.head h1{font-size:22px;margin:0 0 5px}.head p{margin:3px 0;color:#4b5563}.title{text-align:center;font-size:18px;font-weight:700;margin:20px 0}.return-locations{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:18px}.box{border:1px solid #d1d5db;padding:12px;margin-bottom:18px}.return-locations .box{margin-bottom:0}.box strong{display:block;margin-bottom:4px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #cbd5e1;padding:10px;text-align:left}th{background:#fef2f2}.signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:35px;margin-top:90px}.signature{text-align:center;border-top:1px solid #374151;padding-top:7px;font-size:13px}@media print{body{background:#fff}.sheet{margin:0;width:auto;min-height:auto;padding:0}.toolbar{display:none}}</style></head><body><div class="toolbar"><button onclick="window.print()">Print</button></div><main class="sheet"><div class="head"><div><h1><?= htmlspecialchars($company_name) ?></h1><p>Damaged Product Return</p></div><div><strong>Return No: DR-<?= (int)$return['id'] ?></strong><p>Date: <?= htmlspecialchars(app_datetime($return['created_at'])) ?></p><p>Status: <?= htmlspecialchars(ucfirst($return['status'])) ?></p></div></div><div class="title">DAMAGED RETURN NOTE</div><div class="return-locations"><div class="box"><strong>Sent From</strong><?= htmlspecialchars($branch_name) ?></div><div class="box"><strong>Return To</strong>Main Warehouse</div></div><table><thead><tr><th>SL</th><th>Product</th><th>Code</th><th>Variant</th><th>Qty</th></tr></thead><tbody><tr><td>1</td><td><?= htmlspecialchars($return['product_name']) ?></td><td><?= htmlspecialchars($return['sku'] ?? '') ?></td><td><?= htmlspecialchars($return['variant_name'] ?: '-') ?></td><td><?= number_format((float)$return['quantity'], 0) ?></td></tr></tbody></table><div class="box" style="margin-top:18px"><strong>Note</strong><?= htmlspecialchars($return['note'] ?? '') ?></div><div class="signatures"><div class="signature">Prepared By</div><div class="signature">Delivered By</div><div class="signature">Received By</div></div></main></body></html>
