<?php
require_once '../includes/auth.php'; require_once '../includes/db.php'; require_once '../includes/fifo_inventory_helper.php'; require_once '../includes/project_package_helper.php';
$user_id=(int)($_SESSION['user_id']??0);
if(project_package_company_type($conn,$user_id)!=='Fashion house' || !company_multi_branch_enabled($conn,$user_id) || !stock_can_manage_warehouse($conn)){ http_response_code(403); exit('Warehouse access is required.'); }
ensure_fifo_inventory_tables($conn);
$selected_return_id=(int)($_GET['return_id']??0);
$message=$_SESSION['warehouse_damage_message']??''; unset($_SESSION['warehouse_damage_message']); $message_type=$_SESSION['warehouse_damage_message_type']??'success'; unset($_SESSION['warehouse_damage_message_type']); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try { if(!hash_equals(stock_csrf_token(),(string)($_POST['stock_csrf']??''))) throw new RuntimeException('Invalid request token.'); $id=(int)($_POST['return_id']??0); $action=(string)($_POST['action']??''); if($action==='accept') fifo_inventory_accept_damage_return($conn,$user_id,$id); elseif($action==='dump') fifo_inventory_dump_damage_return($conn,$user_id,$id); else throw new RuntimeException('Invalid action.'); $_SESSION['warehouse_damage_message']=$action==='accept'?'Damaged return accepted.':'Dump request sent for admin approval.'; $_SESSION['warehouse_damage_message_type']='success'; } catch(Throwable $e){$_SESSION['warehouse_damage_message']=$e->getMessage(); $_SESSION['warehouse_damage_message_type']='danger';} header('Location: damaged_returns.php'); exit;
}
$returns=mysqli_query($conn,"SELECT dr.*,p.product_name,p.sku,b.branch_name,b.is_head_office FROM stock_damage_returns dr INNER JOIN products p ON p.id=dr.product_id INNER JOIN branches b ON b.id=dr.branch_id WHERE dr.user_id={$user_id} AND dr.status='pending' ORDER BY dr.id DESC LIMIT 500");
$received_history=mysqli_query($conn,"SELECT dr.*,p.product_name,p.sku,b.branch_name,b.is_head_office FROM stock_damage_returns dr INNER JOIN products p ON p.id=dr.product_id INNER JOIN branches b ON b.id=dr.branch_id WHERE dr.user_id={$user_id} AND dr.status IN ('accepted','dump_pending') ORDER BY dr.accepted_at DESC,dr.id DESC LIMIT 500");
$dump_history=mysqli_query($conn,"SELECT dr.*,p.product_name,p.sku,b.branch_name,b.is_head_office FROM stock_damage_returns dr INNER JOIN products p ON p.id=dr.product_id INNER JOIN branches b ON b.id=dr.branch_id WHERE dr.user_id={$user_id} AND dr.status='dumped' ORDER BY dr.dumped_at DESC,dr.id DESC LIMIT 500");
require_once '../includes/header.php'; require_once '../includes/navbar.php'; require_once '../includes/sidebar.php';
?>
<style>.damage-return-selected{background:#fff3cd !important;outline:2px solid #ffc107;outline-offset:-2px}.damage-return-selected td{background:transparent !important}</style>
<section class="content"><div class="container-fluid"><div class="card card-outline card-danger"><div class="card-header"><h3 class="card-title"><i class="fas fa-exclamation-triangle mr-2"></i>Pending Damaged Product Returns</h3></div><div class="card-body">
<?php if($message){?><div class="alert alert-<?=htmlspecialchars($message_type)?>"><?=htmlspecialchars($message)?></div><?php } if($error){?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php } ?>
<div class="table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Date</th><th>Branch</th><th>Product</th><th>Variant</th><th>Qty</th><th>Status</th><th>Note</th><th>Action</th></tr></thead><tbody><?php while($r=mysqli_fetch_assoc($returns)){ $is_selected=(int)$r['id']===$selected_return_id; ?><tr id="damage-return-<?= (int)$r['id'] ?>" class="<?= $is_selected?'damage-return-selected':'' ?>"><td><?=htmlspecialchars(app_datetime($r['created_at']))?></td><td><?=htmlspecialchars($r['is_head_office']?'Head Office':$r['branch_name'])?></td><td><?=htmlspecialchars($r['product_name'])?><?= $r['sku']?' <small class="text-muted">'.htmlspecialchars($r['sku']).'</small>':'' ?></td><td><?=htmlspecialchars($r['variant_name']?:'-')?></td><td><?=number_format((float)$r['quantity'],0)?></td><td><span class="badge badge-<?= $r['status']==='pending'?'warning':($r['status']==='accepted'?'info':'secondary') ?>"><?=htmlspecialchars($r['status']==='dump_pending'?'Dump Pending':ucfirst($r['status']))?></span></td><td><?=htmlspecialchars($r['note'])?></td><td><?php if($r['status']==='pending'){?><form method="post" class="d-inline"><input type="hidden" name="stock_csrf" value="<?=htmlspecialchars(stock_csrf_token())?>"><input type="hidden" name="return_id" value="<?= (int)$r['id'] ?>"><button name="action" value="accept" class="btn btn-sm btn-primary" onclick="return confirm('Accept this damaged return and remove it from branch stock?')">Accept</button></form><?php } elseif($r['status']==='accepted'){?><form method="post" class="d-inline"><input type="hidden" name="stock_csrf" value="<?=htmlspecialchars(stock_csrf_token())?>"><input type="hidden" name="return_id" value="<?= (int)$r['id'] ?>"><button name="action" value="dump" class="btn btn-sm btn-danger" onclick="return confirm('Send this damaged product dump request to admin?')">Dump</button></form><?php } else { echo 'Awaiting admin approval'; } ?></td></tr><?php } ?></tbody></table></div>
</div></div>
<div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-history mr-2"></i>Received Damaged Product History</h3></div><div class="card-body table-responsive"><table class="table table-bordered table-striped mb-0"><thead><tr><th>Received On</th><th>Returned On</th><th>Branch</th><th>Product</th><th>Variant</th><th>Qty</th><th>Status</th><th>Note</th><th>Action</th></tr></thead><tbody><?php if($received_history && mysqli_num_rows($received_history)>0){ while($r=mysqli_fetch_assoc($received_history)){ ?><tr><td><?=htmlspecialchars(app_datetime($r['accepted_at']))?></td><td><?=htmlspecialchars(app_datetime($r['created_at']))?></td><td><?=htmlspecialchars($r['is_head_office']?'Head Office':$r['branch_name'])?></td><td><?=htmlspecialchars($r['product_name'])?><?= $r['sku']?' <small class="text-muted">'.htmlspecialchars($r['sku']).'</small>':'' ?></td><td><?=htmlspecialchars($r['variant_name']?:'-')?></td><td><?=number_format((float)$r['quantity'],0)?></td><td><span class="badge badge-<?= $r['status']==='accepted'?'info':'secondary' ?>"><?=htmlspecialchars($r['status']==='dump_pending'?'Dump Pending':'Received')?></span></td><td><?=htmlspecialchars($r['note'])?></td><td><?php if($r['status']==='accepted'){?><form method="post" class="d-inline"><input type="hidden" name="stock_csrf" value="<?=htmlspecialchars(stock_csrf_token())?>"><input type="hidden" name="return_id" value="<?= (int)$r['id'] ?>"><button name="action" value="dump" class="btn btn-sm btn-danger" onclick="return confirm('Send this damaged product dump request to admin?')">Dump</button></form><?php } else { ?><span class="text-muted">Awaiting admin approval</span><?php } ?></td></tr><?php } }else{ ?><tr><td colspan="9" class="text-center text-muted py-3">No damaged product has been received yet.</td></tr><?php } ?></tbody></table></div></div>
<div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-history mr-2"></i>Damaged Product Dump History</h3></div><div class="card-body table-responsive"><table class="table table-bordered table-striped mb-0"><thead><tr><th>Dumped On</th><th>Returned On</th><th>Branch</th><th>Product</th><th>Variant</th><th>Qty</th><th>Note</th></tr></thead><tbody><?php if($dump_history && mysqli_num_rows($dump_history)>0){ while($r=mysqli_fetch_assoc($dump_history)){ ?><tr><td><?=htmlspecialchars(app_datetime($r['dumped_at']))?></td><td><?=htmlspecialchars(app_datetime($r['created_at']))?></td><td><?=htmlspecialchars($r['is_head_office']?'Head Office':$r['branch_name'])?></td><td><?=htmlspecialchars($r['product_name'])?><?= $r['sku']?' <small class="text-muted">'.htmlspecialchars($r['sku']).'</small>':'' ?></td><td><?=htmlspecialchars($r['variant_name']?:'-')?></td><td><?=number_format((float)$r['quantity'],0)?></td><td><?=htmlspecialchars($r['note'])?></td></tr><?php } }else{ ?><tr><td colspan="7" class="text-center text-muted py-3">No damaged product has been dumped yet.</td></tr><?php } ?></tbody></table></div></div>
</div></section><?php require_once '../includes/footer.php'; ?>
