<?php
require_once '../includes/auth.php'; require_once '../includes/db.php'; require_once '../includes/project_package_helper.php';
$uid=(int)$_SESSION['user_id'];
if(project_package_company_type($conn,$uid)!=='Housing'||(is_manager_user()&&!manager_has_permission('land_ledger'))) die('Access denied');
mysqli_query($conn,"CREATE TABLE IF NOT EXISTS land_entries (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,project_id INT UNSIGNED NOT NULL,entry_type ENUM('Land Purchase','Land Sale','Unused Land') NOT NULL,land_size DECIMAL(12,2) NOT NULL,unit VARCHAR(20) NOT NULL,party VARCHAR(255) NULL,entry_date DATE NULL,note TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(project_id))");
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['delete_land_entry'])){ $deleteId=(int)($_POST['land_entry_id']??0); $delete=mysqli_prepare($conn,'DELETE FROM land_entries WHERE id=? AND user_id=?'); mysqli_stmt_bind_param($delete,'ii',$deleteId,$uid); mysqli_stmt_execute($delete); header('Location: land_manage.php?deleted=1'); exit; }
 $projectId=(int)($_POST['project_id']??0); $type=$_POST['entry_type']??''; $size=(float)($_POST['land_size']??0); $unit=$_POST['unit']??''; $party=trim($_POST['party']??''); $note=trim($_POST['note']??''); $date=DateTime::createFromFormat('d-m-Y',trim($_POST['entry_date']??''));
 if(!$projectId||!in_array($type,['Land Purchase','Land Sale','Unused Land'],true)||$size<=0||!in_array($unit,['Decimal','Katha','Bigha'],true)||!$date) $error='সবগুলো প্রয়োজনীয় তথ্য সঠিকভাবে দিন।';
 else { if($unit==='Katha') $size*=1.65; elseif($unit==='Bigha') $size*=33; $unit='Decimal';
 $stmt=mysqli_prepare($conn,'INSERT INTO land_entries (user_id,project_id,entry_type,land_size,unit,party,entry_date,note) VALUES (?,?,?,?,?,?,?,?)'); $dbDate=$date->format('Y-m-d'); mysqli_stmt_bind_param($stmt,'iisdssss',$uid,$projectId,$type,$size,$unit,$party,$dbDate,$note); if(mysqli_stmt_execute($stmt)){header('Location: land_manage.php?saved=1');exit;} $error='Land entry save করা যায়নি।'; }
}
$projects=mysqli_query($conn,"SELECT id,project_name FROM projects WHERE user_id={$uid} ORDER BY project_name");
$landHistory=mysqli_query($conn,"SELECT le.*,p.project_name FROM land_entries le JOIN projects p ON p.id=le.project_id WHERE le.user_id={$uid} ORDER BY le.entry_date DESC,le.id DESC");
require_once '../includes/header.php'; require_once '../includes/navbar.php'; require_once '../includes/sidebar.php';
?><div class="card"><div class="card-header"><h3>Land Purchase / Sale / Unused Land</h3></div><div class="card-body"><?php if(isset($_GET['saved'])){ ?><div class="alert alert-success">Land entry saved successfully.</div><script>history.replaceState&&history.replaceState({},document.title,'land_manage.php');</script><?php } ?><?php if(isset($_GET['deleted'])){ ?><div class="alert alert-success">Land entry deleted successfully.</div><script>history.replaceState&&history.replaceState({},document.title,'land_manage.php');</script><?php } ?><?php if($error){ ?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php } ?><form method="post"><div class="form-group"><label>Entry Type</label><select name="entry_type" class="form-control"><option>Land Purchase</option><option>Land Sale</option><option>Unused Land</option></select></div><div class="form-group"><label>Select Project</label><select name="project_id" class="form-control" required><option value="">Select Project</option><?php while($p=mysqli_fetch_assoc($projects)){ ?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['project_name'])?></option><?php } ?></select></div><div class="form-row"><div class="form-group col-md-4"><label>Land Size</label><input name="land_size" id="land_size" type="number" step="0.01" class="form-control" required oninput="showDecimalConversion()"><small id="decimal_conversion" class="form-text text-muted" style="display:none"></small></div><div class="form-group col-md-4"><label>Unit</label><select name="unit" id="land_unit" class="form-control" onchange="showDecimalConversion()"><option>Decimal</option><option>Katha</option><option>Bigha</option></select></div><div class="form-group col-md-4"><label>Purchase from / Sale to</label><input name="party" class="form-control"></div></div><div class="form-row"><div class="form-group col-md-4"><label>Date <small class="text-muted">(DD-MM-YYYY)</small></label><div class="input-group"><input name="entry_date" id="entry_date_text" type="text" value="<?=date('d-m-Y')?>" placeholder="DD-MM-YYYY" pattern="\d{2}-\d{2}-\d{4}" class="form-control"><div class="input-group-append"><input id="entry_date_picker" type="date" value="<?=date('Y-m-d')?>" class="form-control" style="max-width:52px;padding:6px" onchange="var d=this.value.split('-');if(d.length===3)document.getElementById('entry_date_text').value=d[2]+'-'+d[1]+'-'+d[0];"></div></div></div><div class="form-group col-md-8"><label>Note</label><input name="note" class="form-control"></div></div><button class="btn btn-primary">Save Entry</button></form>
<hr><h4>Land Entry History</h4><style>.land-history-table{table-layout:fixed}.land-history-table th{white-space:nowrap}.land-history-table .history-date{width:10%}.land-history-table .history-project{width:16%}.land-history-table .history-type{width:13%}.land-history-table .history-size{width:14%}.land-history-table .history-party{width:19%}.land-history-table .history-note{width:22%;word-break:break-word}.land-history-table .history-action{width:6%}</style><div class="table-responsive"><table class="table table-bordered table-striped land-history-table"><thead><tr><th class="history-date">Date</th><th class="history-project">Project</th><th class="history-type">Entry Type</th><th class="history-size">Land Size</th><th class="history-party">Purchase From / Sale To</th><th class="history-note">Note</th><th class="history-action">Action</th></tr></thead><tbody><?php if(mysqli_num_rows($landHistory)){ while($row=mysqli_fetch_assoc($landHistory)){ ?><tr><td class="history-date"><?=$row['entry_date']?date('d-m-Y',strtotime($row['entry_date'])):''?></td><td class="history-project"><?=htmlspecialchars($row['project_name'])?></td><td class="history-type"><?=htmlspecialchars($row['entry_type'])?></td><td class="history-size"><?=number_format((float)$row['land_size'],2)?> <?=htmlspecialchars($row['unit'])?></td><td class="history-party"><?=htmlspecialchars($row['party'])?></td><td class="history-note"><?=htmlspecialchars($row['note'])?></td><td class="history-action"><form method="post" onsubmit="return confirm('Delete this land entry?');"><input type="hidden" name="delete_land_entry" value="1"><input type="hidden" name="land_entry_id" value="<?=$row['id']?>"><button class="btn btn-danger btn-sm" title="Delete"><i class="fas fa-trash"></i></button></form></td></tr><?php }}else{ ?><tr><td colspan="7" class="text-center">No land entry found.</td></tr><?php } ?></tbody></table></div></div></div><script>function showDecimalConversion(){var size=parseFloat(document.getElementById("land_size").value)||0,unit=document.getElementById("land_unit").value,help=document.getElementById("decimal_conversion");if(unit==="Katha"&&size>0){help.textContent="Converted value: "+(size*1.65).toFixed(2)+" Decimal";help.style.display="block";}else if(unit==="Bigha"&&size>0){help.textContent="Converted value: "+(size*33).toFixed(2)+" Decimal";help.style.display="block";}else{help.textContent="";help.style.display="none";}}</script><?php require_once '../includes/footer.php'; ?>
