<?php
require_once '../includes/auth.php';
require_once '../includes/db.php';
require_once '../includes/booking_invoice_helper.php';
require_once '../includes/staff_ledger_helper.php';
require_once '../includes/header.php';
require_once '../includes/navbar.php';
require_once '../includes/sidebar.php';

$user_id=(int)$_SESSION['user_id']; ensure_booking_invoice_table($conn); ensure_booking_invoice_type_table($conn,$user_id); ensure_staff_ledger_table($conn);
$month=isset($_GET['month'])?(int)$_GET['month']:(int)date('m'); $year=isset($_GET['year'])?(int)$_GET['year']:(int)date('Y');
if($month<1||$month>12)$month=(int)date('m'); if($year<2020||$year>2100)$year=(int)date('Y');
function report_scalar($conn,$sql,$types,$values){$stmt=mysqli_prepare($conn,$sql); if(!$stmt)return 0.0; mysqli_stmt_bind_param($stmt,$types,...$values); mysqli_stmt_execute($stmt); $row=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt)); return (float)($row['amount']??0);}
function report_expense_sql($date_sql){return "SELECT COALESCE(SUM(amount),0) amount FROM (SELECT e.amount FROM expenses e WHERE e.user_id=? AND e.approval_status='approved' {$date_sql('e.txn_date')} UNION ALL SELECT l.amount FROM staff_ledger_entries l WHERE l.user_id=? {$date_sql('l.entry_date')}) expense_rows";}
$sales_sql="SELECT COALESCE(SUM(bi.amount),0) amount FROM booking_invoices bi LEFT JOIN booking_invoice_types bit ON bit.user_id=bi.user_id AND bit.type_key=bi.invoice_type WHERE bi.user_id=? AND bi.status='confirmed' AND COALESCE(bit.behavior,'income')='income' AND MONTH(bi.invoice_date)=? AND YEAR(bi.invoice_date)=?";
$total_sales=report_scalar($conn,$sales_sql,'iii',[$user_id,$month,$year]);
$expense_sql="SELECT COALESCE(SUM(amount),0) amount FROM (SELECT e.amount FROM expenses e WHERE e.user_id=? AND e.approval_status='approved' AND MONTH(e.txn_date)=? AND YEAR(e.txn_date)=? UNION ALL SELECT l.amount FROM staff_ledger_entries l WHERE l.user_id=? AND MONTH(l.entry_date)=? AND YEAR(l.entry_date)=?) x";
$total_expenses=report_scalar($conn,$expense_sql,'iiiiii',[$user_id,$month,$year,$user_id,$month,$year]); $net_profit=$total_sales-$total_expenses;

$breakdown_sql="SELECT category_name,SUM(amount) amount FROM (SELECT CONVERT(CONCAT('Expense: ',COALESCE(c.category_name,'General')) USING utf8mb4) COLLATE utf8mb4_unicode_ci category_name,e.amount FROM expenses e LEFT JOIN categories c ON c.id=e.category_id WHERE e.user_id=? AND e.approval_status='approved' AND MONTH(e.txn_date)=? AND YEAR(e.txn_date)=? UNION ALL SELECT CONVERT(CONCAT('Staff ',UPPER(LEFT(l.entry_type,1)),SUBSTRING(l.entry_type,2)) USING utf8mb4) COLLATE utf8mb4_unicode_ci category_name,l.amount FROM staff_ledger_entries l WHERE l.user_id=? AND MONTH(l.entry_date)=? AND YEAR(l.entry_date)=?) x GROUP BY category_name ORDER BY amount DESC,category_name";
$stmt=mysqli_prepare($conn,$breakdown_sql); mysqli_stmt_bind_param($stmt,'iiiiii',$user_id,$month,$year,$user_id,$month,$year); mysqli_stmt_execute($stmt); $result=mysqli_stmt_get_result($stmt); $breakdown=[]; while($row=mysqli_fetch_assoc($result))$breakdown[]=$row;

$month_labels=[];$month_sales=[];$month_expenses=[];for($m=1;$m<=12;$m++){ $month_labels[]=date('M',mktime(0,0,0,$m,1));$month_sales[$m]=0.0;$month_expenses[$m]=0.0; }
$stmt=mysqli_prepare($conn,"SELECT MONTH(bi.invoice_date) m,SUM(bi.amount) amount FROM booking_invoices bi LEFT JOIN booking_invoice_types bit ON bit.user_id=bi.user_id AND bit.type_key=bi.invoice_type WHERE bi.user_id=? AND bi.status='confirmed' AND COALESCE(bit.behavior,'income')='income' AND YEAR(bi.invoice_date)=? GROUP BY MONTH(bi.invoice_date)"); mysqli_stmt_bind_param($stmt,'ii',$user_id,$year);mysqli_stmt_execute($stmt);$result=mysqli_stmt_get_result($stmt);while($row=mysqli_fetch_assoc($result))$month_sales[(int)$row['m']]=(float)$row['amount'];
$stmt=mysqli_prepare($conn,"SELECT m,SUM(amount) amount FROM (SELECT MONTH(e.txn_date) m,e.amount FROM expenses e WHERE e.user_id=? AND e.approval_status='approved' AND YEAR(e.txn_date)=? UNION ALL SELECT MONTH(l.entry_date) m,l.amount FROM staff_ledger_entries l WHERE l.user_id=? AND YEAR(l.entry_date)=?) x GROUP BY m");mysqli_stmt_bind_param($stmt,'iiii',$user_id,$year,$user_id,$year);mysqli_stmt_execute($stmt);$result=mysqli_stmt_get_result($stmt);while($row=mysqli_fetch_assoc($result))$month_expenses[(int)$row['m']]=(float)$row['amount'];

$start_year=$year-4;$year_labels=[];$year_sales=[];$year_expenses=[];for($y=$start_year;$y<=$year;$y++){ $year_labels[]=(string)$y;$year_sales[$y]=0.0;$year_expenses[$y]=0.0; }
$stmt=mysqli_prepare($conn,"SELECT YEAR(bi.invoice_date) y,SUM(bi.amount) amount FROM booking_invoices bi LEFT JOIN booking_invoice_types bit ON bit.user_id=bi.user_id AND bit.type_key=bi.invoice_type WHERE bi.user_id=? AND bi.status='confirmed' AND COALESCE(bit.behavior,'income')='income' AND YEAR(bi.invoice_date) BETWEEN ? AND ? GROUP BY YEAR(bi.invoice_date)");mysqli_stmt_bind_param($stmt,'iii',$user_id,$start_year,$year);mysqli_stmt_execute($stmt);$result=mysqli_stmt_get_result($stmt);while($row=mysqli_fetch_assoc($result))$year_sales[(int)$row['y']]=(float)$row['amount'];
$stmt=mysqli_prepare($conn,"SELECT y,SUM(amount) amount FROM (SELECT YEAR(e.txn_date) y,e.amount FROM expenses e WHERE e.user_id=? AND e.approval_status='approved' AND YEAR(e.txn_date) BETWEEN ? AND ? UNION ALL SELECT YEAR(l.entry_date) y,l.amount FROM staff_ledger_entries l WHERE l.user_id=? AND YEAR(l.entry_date) BETWEEN ? AND ?) x GROUP BY y");mysqli_stmt_bind_param($stmt,'iiiiii',$user_id,$start_year,$year,$user_id,$start_year,$year);mysqli_stmt_execute($stmt);$result=mysqli_stmt_get_result($stmt);while($row=mysqli_fetch_assoc($result))$year_expenses[(int)$row['y']]=(float)$row['amount'];
?>
<section class="content"><div class="container-fluid">
<div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-coins mr-2"></i>Profit Report</h3></div><div class="card-body"><form method="get"><div class="row align-items-end"><div class="col-md-3"><label>Month</label><select name="month" class="form-control"><?php for($m=1;$m<=12;$m++){?><option value="<?=$m?>" <?=$month===$m?'selected':''?>><?=date('F',mktime(0,0,0,$m,1))?></option><?php }?></select></div><div class="col-md-3"><label>Year</label><select name="year" class="form-control"><?php for($y=(int)date('Y');$y>=2020;$y--){?><option value="<?=$y?>" <?=$year===$y?'selected':''?>><?=$y?></option><?php }?></select></div><div class="col-md-2"><button class="btn btn-primary btn-block"><i class="fas fa-filter"></i> Filter</button></div><div class="col-md-2"><button type="button" class="btn btn-info btn-block" onclick="window.print()"><i class="fas fa-print"></i> Print</button></div><div class="col-md-2"><a href="profit_report.php" class="btn btn-secondary btn-block"><i class="fas fa-redo"></i> This Month</a></div></div></form></div></div>
<div class="report-print-heading d-none">
    <div class="print-brand">YOU2 <span>TECHNOLOGIES</span></div>
    <div class="print-document-title">Profit Report</div>
    <div class="print-report-meta"><span>Report period: <?=date('F Y',mktime(0,0,0,$month,1,$year))?></span><span>Generated: <?=date('d M Y, h:i A')?></span></div>
</div>
<div class="row"><div class="col-md-4"><div class="small-box bg-primary"><div class="inner"><h3>BDT <?=number_format($total_sales,2)?></h3><p>Total Sales</p></div><div class="icon"><i class="fas fa-chart-line"></i></div></div></div><div class="col-md-4"><div class="small-box bg-danger"><div class="inner"><h3>BDT <?=number_format($total_expenses,2)?></h3><p>Total Expenses</p></div><div class="icon"><i class="fas fa-receipt"></i></div></div></div><div class="col-md-4"><div class="small-box bg-<?=$net_profit>=0?'success':'warning'?>"><div class="inner"><h3>BDT <?=number_format($net_profit,2)?></h3><p>Net Profit</p></div><div class="icon"><i class="fas fa-wallet"></i></div></div></div></div>
<div class="row"><div class="col-md-6"><div class="card"><div class="card-header"><h3 class="card-title">Monthly Sales vs Expense — <?=$year?></h3></div><div class="card-body"><div style="height:330px"><canvas id="monthlyChart"></canvas></div></div></div></div><div class="col-md-6"><div class="card"><div class="card-header"><h3 class="card-title">Yearly Sales vs Expense</h3></div><div class="card-body"><div style="height:330px"><canvas id="yearlyChart"></canvas></div></div></div></div></div>
<div class="row"><div class="col-md-6"><div class="card"><div class="card-header"><h3 class="card-title">Profit Calculation</h3></div><div class="card-body p-0"><table class="table table-bordered mb-0"><tbody><tr><th>Total Sales</th><td class="text-right">BDT <?=number_format($total_sales,2)?></td></tr><tr><th>Less: Total Expenses</th><td class="text-right text-danger">− BDT <?=number_format($total_expenses,2)?></td></tr><tr class="<?=$net_profit>=0?'table-success':'table-danger'?>"><th>Net Profit</th><th class="text-right">BDT <?=number_format($net_profit,2)?></th></tr></tbody></table></div></div></div><div class="col-md-6"><div class="card"><div class="card-header"><h3 class="card-title">Expense Breakdown</h3></div><div class="card-body p-0"><table class="table table-bordered mb-0"><thead><tr><th>Category</th><th class="text-right">Amount</th></tr></thead><tbody><?php foreach($breakdown as $item){?><tr><td><?=htmlspecialchars($item['category_name'])?></td><td class="text-right">BDT <?=number_format($item['amount'],2)?></td></tr><?php }if(empty($breakdown)){?><tr><td colspan="2" class="text-center text-muted">No expenses for this month.</td></tr><?php }?></tbody><tfoot><tr><th>Total Expenses</th><th class="text-right">BDT <?=number_format($total_expenses,2)?></th></tr></tfoot></table></div></div></div></div>
</div></section>
<?php $page_script='<script>var chartOptions={responsive:true,maintainAspectRatio:false,scales:{yAxes:[{ticks:{beginAtZero:true}}]}};new Chart(document.getElementById("monthlyChart"),{type:"bar",data:{labels:'.json_encode($month_labels).',datasets:[{label:"Sales",data:'.json_encode(array_values($month_sales)).',backgroundColor:"#1677e8"},{label:"Expense",data:'.json_encode(array_values($month_expenses)).',backgroundColor:"#dc3545"}]},options:chartOptions});new Chart(document.getElementById("yearlyChart"),{type:"bar",data:{labels:'.json_encode($year_labels).',datasets:[{label:"Sales",data:'.json_encode(array_values($year_sales)).',backgroundColor:"#28a745"},{label:"Expense",data:'.json_encode(array_values($year_expenses)).',backgroundColor:"#ffc107"}]},options:chartOptions});</script><style>@page{size:A4 landscape;margin:10mm}@media print{html,body{background:#fff!important;color:#14213d!important;font-size:10px!important}.main-header,.main-sidebar,.main-footer,.card:first-child,.btn{display:none!important}.content-wrapper,.content,.container-fluid{margin:0!important;padding:0!important;width:100%!important;min-height:0!important}.report-print-heading{display:block!important;border-bottom:2px solid #1677e8!important;padding:0 0 10px!important;margin:0 0 12px!important;text-align:center!important}.report-print-heading h2{font-size:20px!important;letter-spacing:1px!important;margin:0 0 4px!important;color:#0b2e59!important}.report-print-heading strong{font-size:11px!important;color:#5d6b82!important}.row{display:flex!important;flex-wrap:wrap!important;margin:0 -4px!important}.row>.col-md-4{flex:0 0 33.333%!important;max-width:33.333%!important;padding:0 4px!important}.row>.col-md-6{flex:0 0 50%!important;max-width:50%!important;padding:0 4px!important}.card{box-shadow:none!important;border:1px solid #d9e2ef!important;border-radius:0!important;margin-bottom:8px!important;break-inside:avoid!important}.card-header{background:#f3f7fc!important;border-bottom:1px solid #d9e2ef!important;padding:7px 10px!important;font-weight:700!important}.card-body{padding:8px!important}.small-box{background:#fff!important;border:1px solid #d9e2ef!important;box-shadow:none!important;min-height:auto!important;margin-bottom:8px!important;color:#14213d!important}.small-box h3,.small-box p{color:#14213d!important}.small-box h3{font-size:17px!important;margin:0!important}.small-box p{font-size:10px!important;margin:3px 0 0!important}.small-box .icon{display:none!important}canvas{max-height:150px!important}table{width:100%!important;font-size:9px!important;border-collapse:collapse!important}th{background:#eaf2fb!important;color:#12375d!important}th,td{padding:5px!important;border:1px solid #d9e2ef!important}.bg-success,.bg-danger,.bg-warning{background:#fff!important;color:#14213d!important}}</style>';require_once '../includes/footer.php';?>
