<?php
require_once '../includes/auth.php'; require_once '../includes/db.php'; require_once '../includes/staff_helper.php';
ensure_staff_table($conn); $user_id=(int)$_SESSION['user_id'];
if(isset($_GET['toggle']) && manager_can_modify()){
 $id=(int)$_GET['toggle']; $stmt=mysqli_prepare($conn,"UPDATE staff SET status=IF(status='active','inactive','active') WHERE id=? AND user_id=?"); mysqli_stmt_bind_param($stmt,'ii',$id,$user_id); mysqli_stmt_execute($stmt); header('Location:index.php'); exit;
}
$stmt=mysqli_prepare($conn,"SELECT * FROM staff WHERE user_id=? ORDER BY id DESC"); mysqli_stmt_bind_param($stmt,'i',$user_id); mysqli_stmt_execute($stmt); $staff=mysqli_stmt_get_result($stmt);
require_once '../includes/header.php'; require_once '../includes/navbar.php'; require_once '../includes/sidebar.php'; ?>
<div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-users mr-2"></i>Staff List</h3><?php if(manager_can_modify()){ ?><div class="card-tools"><a href="create.php" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Create Staff</a></div><?php } ?></div><div class="card-body"><table id="example1" class="table table-bordered table-striped"><thead><tr><th>Staff ID</th><th>Name</th><th>Phone</th><th>Address</th><th>Designation</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($row=mysqli_fetch_assoc($staff)){ $used=staff_has_transactions($conn,$row['id']); ?><tr><td><?=htmlspecialchars($row['staff_code'] ?: staff_code_from_id($row['id']))?></td><td><?=htmlspecialchars($row['name'])?></td><td><?=htmlspecialchars($row['phone'])?></td><td><?=htmlspecialchars($row['address'] ?? '')?></td><td><?=htmlspecialchars($row['designation'] ?? '')?></td><td><span class="badge badge-<?=$row['status']==='active'?'success':'secondary'?>"><?=htmlspecialchars($row['status'])?></span></td><td><a class="btn btn-info btn-sm" href="profile.php?id=<?=$row['id']?>"><i class="fas fa-user"></i> Profile</a><?php if(manager_can_modify()){ ?><a class="btn btn-sm btn-<?=$row['status']==='active'?'secondary':'success'?>" href="index.php?toggle=<?=$row['id']?>"><?=$row['status']==='active'?'Inactive':'Active'?></a><?php if(!$used){ ?><a class="btn btn-warning btn-sm" href="edit.php?id=<?=$row['id']?>"><i class="fas fa-edit"></i></a><a class="btn btn-danger btn-sm" onclick="return confirm('Delete staff?')" href="delete.php?id=<?=$row['id']?>"><i class="fas fa-trash"></i></a><?php }else{ ?><span class="text-muted small ml-1">Delete locked</span><?php } ?><?php } ?></td></tr><?php } ?></tbody></table></div></div><?php require_once '../includes/footer.php'; ?>
