<?php
require_once '../includes/auth.php'; require_once '../includes/db.php'; require_once '../includes/staff_helper.php';
ensure_staff_table($conn); $user_id=(int)$_SESSION['user_id'];
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action'] ?? '') === 'ajax_staff_action'){
 header('Content-Type: application/json');
 $id=(int)($_POST['staff_id'] ?? 0); $staff_action=$_POST['staff_action'] ?? '';
 $staff_stmt=mysqli_prepare($conn,"SELECT id,status FROM staff WHERE id=? AND user_id=? LIMIT 1"); mysqli_stmt_bind_param($staff_stmt,'ii',$id,$user_id); mysqli_stmt_execute($staff_stmt); $staff_row=mysqli_fetch_assoc(mysqli_stmt_get_result($staff_stmt));
 if(!$staff_row){ http_response_code(404); echo json_encode(['success'=>false,'message'=>'Staff not found.']); exit; }
 if($staff_action==='toggle'){
  if(!manager_can_modify()){ http_response_code(403); echo json_encode(['success'=>false,'message'=>'Permission denied.']); exit; }
  $new_status=$staff_row['status']==='active' ? 'inactive' : 'active'; $update=mysqli_prepare($conn,"UPDATE staff SET status=? WHERE id=? AND user_id=?"); mysqli_stmt_bind_param($update,'sii',$new_status,$id,$user_id); mysqli_stmt_execute($update); echo json_encode(['success'=>true,'status'=>$new_status]); exit;
 }
 if($staff_action==='delete'){
  if(!manager_can_modify() || staff_has_transactions($conn,$id)){ http_response_code(422); echo json_encode(['success'=>false,'message'=>'This staff cannot be deleted.']); exit; }
  $delete=mysqli_prepare($conn,"DELETE FROM staff WHERE id=? AND user_id=?"); mysqli_stmt_bind_param($delete,'ii',$id,$user_id); mysqli_stmt_execute($delete); echo json_encode(['success'=>true,'deleted'=>true]); exit;
 }
 http_response_code(422); echo json_encode(['success'=>false,'message'=>'Invalid action.']); exit;
}
if(isset($_GET['toggle']) && manager_can_modify()){
 $id=(int)$_GET['toggle']; $stmt=mysqli_prepare($conn,"UPDATE staff SET status=IF(status='active','inactive','active') WHERE id=? AND user_id=?"); mysqli_stmt_bind_param($stmt,'ii',$id,$user_id); mysqli_stmt_execute($stmt); header('Location:index.php'); exit;
}
$stmt=mysqli_prepare($conn,"SELECT * FROM staff WHERE user_id=? ORDER BY id DESC"); mysqli_stmt_bind_param($stmt,'i',$user_id); mysqli_stmt_execute($stmt); $staff=mysqli_stmt_get_result($stmt);
require_once '../includes/header.php'; require_once '../includes/navbar.php'; require_once '../includes/sidebar.php'; ?>
<div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-users mr-2"></i>Staff List</h3><?php if(manager_can_modify()){ ?><div class="card-tools"><a href="create.php" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Create Staff</a></div><?php } ?></div><div class="card-body"><table id="example1" class="table table-bordered table-striped"><thead><tr><th>Staff ID</th><th>Name</th><th>Email</th><th>Phone</th><th>Address</th><th>Designation</th><th>Salary</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($row=mysqli_fetch_assoc($staff)){ $used=staff_has_transactions($conn,$row['id']); ?><tr data-staff-id="<?= (int)$row['id'] ?>"><td><?=htmlspecialchars($row['staff_code'] ?: staff_code_from_id($row['id']))?></td><td><?=htmlspecialchars($row['name'])?></td><td><?=htmlspecialchars($row['email'] ?? '')?></td><td><?=htmlspecialchars($row['phone'])?></td><td><?=htmlspecialchars($row['address'] ?? '')?></td><td><?=htmlspecialchars($row['designation'] ?? '')?></td><td>BDT <?=number_format((float)($row['salary'] ?? 0), 2)?></td><td><span class="badge staff-status-badge badge-<?=$row['status']==='active'?'success':'secondary'?>"><?=htmlspecialchars($row['status'])?></span></td><td><a class="btn btn-info btn-sm" href="profile.php?id=<?=$row['id']?>" title="Profile"><i class="fas fa-user"></i></a><?php if(manager_can_modify()){ ?><button type="button" class="btn btn-sm staff-ajax-action staff-toggle-action btn-<?=$row['status']==='active'?'secondary':'success'?>" data-staff-id="<?= (int)$row['id'] ?>" data-staff-action="toggle" title="<?=$row['status']==='active'?'Make Inactive':'Make Active'?>"><i class="fas <?=$row['status']==='active'?'fa-toggle-off':'fa-toggle-on'?>"></i></button><a class="btn btn-warning btn-sm" href="edit.php?id=<?=$row['id']?>" title="Edit"><i class="fas fa-edit"></i></a><?php if(!$used){ ?><button type="button" class="btn btn-danger btn-sm staff-ajax-action" data-staff-id="<?= (int)$row['id'] ?>" data-staff-action="delete" title="Delete"><i class="fas fa-trash"></i></button><?php }else{ ?><button type="button" class="btn btn-secondary btn-sm" disabled title="This staff has transactions and cannot be deleted"><i class="fas fa-trash"></i></button><?php } ?><?php } ?></td></tr><?php } ?></tbody></table></div></div>
<script>document.addEventListener('click',async function(event){const button=event.target.closest('.staff-ajax-action');if(!button||button.disabled)return;const action=button.dataset.staffAction;if(action==='delete'&&!confirm('Delete this staff?'))return;button.disabled=true;try{const response=await fetch('index.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},body:new URLSearchParams({action:'ajax_staff_action',staff_id:button.dataset.staffId,staff_action:action})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Action could not be completed.');const row=button.closest('tr');if(action==='delete'){if(window.jQuery&&jQuery.fn.DataTable&&jQuery.fn.DataTable.isDataTable('#example1'))jQuery('#example1').DataTable().row(row).remove().draw(false);else row.remove();return;}const active=data.status==='active';const badge=row.querySelector('.staff-status-badge');badge.textContent=data.status;badge.className='badge staff-status-badge '+(active?'badge-success':'badge-secondary');button.className='btn btn-sm staff-ajax-action staff-toggle-action '+(active?'btn-secondary':'btn-success');button.title=active?'Make Inactive':'Make Active';button.innerHTML=active?'<i class="fas fa-toggle-off"></i>':'<i class="fas fa-toggle-on"></i>';}catch(error){alert(error.message||'Action could not be completed.');}finally{button.disabled=false;}});</script>
<?php require_once '../includes/footer.php'; ?>
