        </div>
    </section>
</div>

<footer class="main-footer">

    <strong>
You2 Biz &copy; <?= date('Y'); ?>
    </strong>

</footer>

</div>

<?php $app_root_path = function_exists('app_root_path') ? app_root_path() : ''; ?>

<!-- jQuery -->
<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/plugins/jquery/jquery.min.js'); ?>"></script>

<!-- Bootstrap -->
<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js'); ?>"></script>

<!-- DataTables -->
<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/plugins/datatables/jquery.dataTables.min.js'); ?>"></script>

<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js'); ?>"></script>

<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js'); ?>"></script>

<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js'); ?>"></script>

<!-- Select2 -->
<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/plugins/select2/js/select2.full.min.js'); ?>"></script>

<!-- Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<!-- AdminLTE -->
<script src="<?= htmlspecialchars(($app_root_path === '' ? '' : $app_root_path) . '/adminlte/dist/js/adminlte.min.js'); ?>"></script>

<script>

$(function () {

    $("table.table").each(function(){

        if(!$(this).parent().hasClass("table-responsive")){

            $(this).wrap(
                '<div class="table-responsive"></div>'
            );

        }

    });

    if($("#example1").length){

        var example1Responsive = !$("#example1").is("[data-desktop-table]");

        $("#example1").DataTable({

            "responsive": example1Responsive,
            "autoWidth": false,
            "order": []

        });

    }

});

</script>
<?php
if (isset($page_script)) {
    echo $page_script;
}
?>

<style>
@media print {
    .report-print-heading {
        position: relative !important;
        display: block !important;
        text-align: left !important;
        border-top: 7px solid #1677e8 !important;
        border-bottom: 1px solid #ccd8e8 !important;
        padding: 13px 0 9px !important;
        margin: 0 0 12px !important;
    }
    .report-print-heading .print-brand {
        color: #0b2e59 !important;
        font-size: 19px !important;
        font-weight: 800 !important;
        letter-spacing: 1.4px !important;
        line-height: 1.1 !important;
    }
    .report-print-heading .print-brand span {
        color: #1677e8 !important;
        font-weight: 500 !important;
    }
    .report-print-heading .print-document-title {
        color: #14213d !important;
        font-size: 15px !important;
        font-weight: 700 !important;
        letter-spacing: 1.1px !important;
        margin-top: 5px !important;
        text-transform: uppercase !important;
    }
    .report-print-heading .print-report-meta {
        border-top: 1px solid #e2e9f2 !important;
        color: #5d6b82 !important;
        display: flex !important;
        font-size: 9px !important;
        justify-content: space-between !important;
        margin-top: 7px !important;
        padding-top: 6px !important;
    }
    .report-print-heading ~ .row .small-box {
        border-top: 3px solid #1677e8 !important;
        padding: 4px !important;
    }
    .report-print-heading ~ .row .small-box h3 { font-size: 20px !important; }
    .report-print-heading ~ .card .card-header .card-title,
    .report-print-heading ~ .row .card-header .card-title {
        color: #12375d !important;
        font-size: 12px !important;
        font-weight: 700 !important;
    }
    .report-print-heading ~ .card .card-body > div[style],
    .report-print-heading ~ .row .card-body > div[style] { height: 210px !important; }
    .report-print-heading ~ .card,
    .report-print-heading ~ .row .card { page-break-inside: avoid !important; }
    .report-print-heading ~ .card tfoot th,
    .report-print-heading ~ .card tfoot td,
    .report-print-heading ~ .row tfoot th,
    .report-print-heading ~ .row tfoot td {
        background: #edf4fb !important;
        font-weight: 700 !important;
    }
    .report-print-heading ~ .card:last-child { margin-bottom: 0 !important; }
    .report-print-heading ~ .card:last-child:after,
    .report-print-heading ~ .row:last-child:after {
        border-top: 1px solid #dce5ef !important;
        color: #6a7890 !important;
        content: "This report is system generated by You2 Technologies" !important;
        display: block !important;
        font-size: 8px !important;
        margin-top: 8px !important;
        padding-top: 5px !important;
        text-align: center !important;
    }
}
</style>

</body>
</html>
